### ISSUE TITLE
Charpter 2 正态分布图片问题

### ISSUE THREAD

**Issue by baizelan** [xiaolai/time-as-a-friend#10]

**Comment by baizelan** [comment]
第二章中的正态分布配图的兔子漫画应该为最富足的兔子在最右边，最穷困的兔子在最右边，请笑来老师对照一下

![](https://github.com/xiaolai/time-as-a-friend/blob/master/images/041_Image_1.png)

**Comment by xiaolai** [comment]
哈哈，是呀。
