### ISSUE TITLE
关于本书第二章“资源分配不均”的一个问题。

### ISSUE THREAD

**Issue by xu-kai-xu** [xiaolai/time-as-a-friend#19]
您在第二章第六节介绍**资源分配不均**的问题上，借用了正态分布的例子，说明

> 只有极少数人在资源上极端贫困，也只有极少数人在资源上极端富有，绝大多数人属于中等水平。

我想知道这一结论是您凭直觉获得的（intuative）还是从以往的研究中得到的结论。

因为在经济学中有个[**帕累托法则**](https://zh.wikipedia.org/wiki/%E5%B8%95%E7%B4%AF%E6%89%98%E6%B3%95%E5%88%99)，它大概讲的是
> 意大利约有80％的土地由20％的人口所有。
相似的分布规律也出现在其他经济领域。

然后，帕累托法则在统计学上其实是一种幂律分布。这一定律应该算是已经被证实并且被广泛接受的。那么，我觉得财富分配不是按您说的那样，符合正态分布（假如是正态分布的话，反而会更好一点），而是符合幂律分布。这样的话，就会造成一种非常不均衡的财富分配情况（可以参考知乎上的一个帖子[**财富分配可能天生不公平**](https://zhuanlan.zhihu.com/p/58116077)）。

这样的话，造成的结果，就不是您所说的，**只有极少数人在资源商极端贫困，也只有极少数人在资源上极端富有，绝大多数人属于中等水平**，而是

> 只有极少数人在资源上极端富有，而绝大多数人在资源上极端贫困。

同样是资源分配不均，幂律分布比正态分布要不均得多得多。
是我的一个疑问，不影响文章想要表达的内容。

**Comment by xiaolai** [comment]
有人反应过这个问题，我一直没更新。找时间吧。
